# pixel_battle/scripts/dump_timeline.py
"""Convert a legacy condition-script YAML into a candidate timeline YAML by
simulating the fight and logging every non-idle action emit per side.

Usage:
    python -m pixel_battle.scripts.dump_timeline \\
        pixel_battle/data/scripts/legacy/01_lux_kite_garen.yaml \\
        pixel_battle/data/scripts/01_lux_kite_garen.yaml

The output is a STARTING POINT — the author rounds timestamps to 100 ms,
trims misses, and adds prose chapter comments.
"""
from __future__ import annotations
import argparse
import os
from pathlib import Path

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

import yaml

from pixel_battle.rl.env import PixelBattleEnv
from pixel_battle.script.driver import ScriptDriver
from pixel_battle.script.loader import load_script, DO_VERBS


_ACTION_TO_VERB = {v: k for k, v in DO_VERBS.items()}
TICK_MS = 16
MAX_MS = 60_000


def _engine_action_to_do(action_int: int) -> str:
    """Map action int back to a `do` verb string. Same as DO_VERBS reverse."""
    if action_int in _ACTION_TO_VERB:
        return _ACTION_TO_VERB[action_int]
    return f"unknown:{action_int}"


def dump_timeline_for(legacy_path: Path, out_path: Path) -> None:
    script = load_script(legacy_path)
    driver = ScriptDriver(script)
    env = PixelBattleEnv(left_id=script.left, right_id=script.right)
    env.reset()

    left_events = []
    right_events = []
    last_left_action = 0
    last_right_action = 0
    while env.battle.elapsed_ms < MAX_MS and not env.battle.state.name == "KO":
        left_act, right_act = driver.decide(env.battle)
        t = env.battle.elapsed_ms
        # Log a transition into a non-idle action (or any change away from idle)
        if left_act != 0 and left_act != last_left_action:
            left_events.append({"t": t, "do": _engine_action_to_do(left_act)})
        if right_act != 0 and right_act != last_right_action:
            right_events.append({"t": t, "do": _engine_action_to_do(right_act)})
        last_left_action = left_act
        last_right_action = right_act
        # env.step takes a single (left_act, right_act) tuple
        env.step((left_act, right_act))

    data = {
        "name": script.name,
        "left": script.left,
        "right": script.right,
        "duration_ms": env.battle.elapsed_ms,
        "left_timeline": left_events,
        "right_timeline": right_events,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "# Generated by dump_timeline.py — round timestamps to 100 ms, "
        "trim out_of_range emissions, add prose chapter headers.\n"
        + yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("legacy", type=Path, help="legacy condition-script YAML")
    p.add_argument("out", type=Path, help="output timeline YAML")
    args = p.parse_args()
    dump_timeline_for(args.legacy, args.out)
    print(f"wrote {args.out}")
